parameters:
    medias_directory: 'public/uploads'
    uploads_directory: 'uploads/'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Twig\AppExtension:
        tags:
            - { name: twig.extension }
